# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
title: Hope is an expensive emotion.
baseurl: "/site" # the subpath of your site, e.g. /blog
url: 'https://fransden.github.io' # "http://vanhaelewijck.com" # the base hostname & protocol for your site, e.g. http://example.com